name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instala dependências
        run: npm install

      - name: Executa testes Cypress
        run: npx cypress run
